### ISSUE TITLE
Localisation File Not Working

### ISSUE THREAD

**Issue by Worheda** [kayila/stellaris-xenomorphs#1]
The Localisation file is not set up properly, resulting in localization not appearing in-game. The file should have a space at the beginning of every line.

**Comment by Worheda** [comment]
Ok, I actually found a secondary issue with the Localisation file. The file is encoded with UTF-8, when it needs to be encoded with UTF-8-BOM.

**Comment by kayila** [comment]
Yea, I noticed this last night as well. Working on fixing it, Stellaris was doing some weird things that was hindering me.

**Comment by kayila** [comment]
Fixed in 57be5996e7c9a572caffcb4dd7c4c12f37e53c70
